workflows:
  flutter-flavors-android-dev:
    name: Android Flutter Flavors Dev
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      groups:
        - environment
      flutter: stable
    triggering:
      events:
        - pull_request
        - tag
        - push
      branch_patterns:
        - pattern: "duy/27-fix-upgrade-to-sdk-version-34-to-meet-requirements-customizable-picker-image-package"
          include: true
          source: true
    scripts:
      - name: Configuration .env files
        script: |
          echo "BASE_URL=$BASE_URL" >> assets/env/.env
          echo "BASE_URL=$BASE_URL_DEV" >> assets/env/.env.dev
          echo "BASE_URL=$BASE_URL_STAG" >> assets/env/.env.staging
      - name: Get Flutter Packages
        script: |
          flutter clean
          flutter pub get
      - name: Run Flutter Test
        script: |
          flutter test
      - name: Flutter build apk with flavors
        script: |
          flutter build apk -t lib/flavors/main_production.dart --flavor=prod --release --no-tree-shake-icons
          flutter build apk -t lib/flavors/main_development.dart --flavor=dev --release --no-tree-shake-icons
          flutter build apk -t lib/flavors/main_staging.dart --flavor=staging --release --no-tree-shake-icons
    artifacts:
      - ./build/app/outputs/flutter-apk/app-dev-release.apk
      - ./build/app/outputs/flutter-apk/app-prod-release.apk
      - ./build/app/outputs/flutter-apk/app-staging-release.apk
    publishing:
      email:
        recipients:
          - tduy24699@gmail.com
          - gianghobagai@gmail.com
          - ntsinh.dev@gmail.com
          - Boigaming1411@gmail.com
        notify:
          success: true
          failure: false
      # app_store_connect:
      #   api_key: $APP_STORE_CONNECT_PRIVATE_KEY # Contents of the API key, can also reference environment variable such as $APP_STORE_CONNECT_PRIVATE_KEY
      #   key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER # Alphanumeric value that identifies the API key, can also reference environment variable such as $APP_STORE_CONNECT_KEY_IDENTIFIER
      #   issuer_id: $APP_STORE_CONNECT_ISSUER_ID # Alphanumeric value that identifies who created the API key, can also reference environment variable such as $APP_STORE_CONNECT_ISSUER_ID
  # flutter-flavors-ios-prod:
  #   name: iOS Flutter Flavors Prod
  #   instance_type: mac_mini_m2
  #   max_build_duration: 120
  #   working_directory: flutter/flutter-flavors-demo-project
  #   environment:
  #     groups:
  #       # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
  #       - ios_creds # <-- (group contains variables: APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY, CERTIFICATE_PRIVATE_KEY)
  #     vars:
  #       XCODE_WORKSPACE: "ios/Runner.xcworkspace" # <-- Put your encrypted Certificate Private Key here
  #       # Environment variable values provided when triggering build with Codemagic API. Alternatively add the required values below.
  #       APP_STORE_APP_ID: 1589804841 # <-- Put the app id number here. This is found in App Store Connect > App > General > App Information
  #       XCODE_CONFIG: Release-prod
  #       XCODE_SCHEME: prod
  #       BUNDLE_ID: io.codemagic.flutterflavors.prod
  #       ENTRY_POINT: lib/main_prod.dart
  #     flutter: stable
  #     xcode: 14.3
  #     cocoapods: default
  #   triggering:
  #     events:
  #       - push
  #     branch_patterns:
  #       - pattern: "main"
  #         include: true
  #         source: true
  #   scripts:
  #     - name: Get Flutter Packages
  #       script: |
  #         flutter packages pub get
  #     - name: Pod install
  #       script: |
  #         find . -name "Podfile" -execdir pod install \;
  #     - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
  #       script: |
  #         keychain initialize
  #     - name: Fetch signing files
  #       script: |
  #         app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
  #     - name: Add certs to keychain
  #       script: |
  #         keychain add-certificates
  #     - name: Set up code signing settings on Xcode project
  #       script: |
  #         xcode-project use-profiles
  #     - name: Flutter build ipa and automatic versioning
  #       script: |
  #         flutter build ipa --release \
  #         --build-name=1.0.0 \
  #         --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1)) \
  #         --export-options-plist=/Users/builder/export_options.plist \
  #         --flavor="$XCODE_SCHEME" \
  #         -t "$ENTRY_POINT"
  #   artifacts:
  #     - build/ios/ipa/*.ipa
  #     - /tmp/xcodebuild_logs/*.log
  #     - flutter_drive.log
  #     - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
  #   publishing:
  #     email:
  #       recipients:
  #         - user_1@example.com
  #         - user_2@example.com
  #       notify:
  #         success: true
  #         failure: true
  #     app_store_connect:
  #       api_key: $APP_STORE_CONNECT_PRIVATE_KEY # Contents of the API key, can also reference environment variable such as $APP_STORE_CONNECT_PRIVATE_KEY
  #       key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER # Alphanumeric value that identifies the API key, can also reference environment variable such as $APP_STORE_CONNECT_KEY_IDENTIFIER
  #       issuer_id: $APP_STORE_CONNECT_ISSUER_ID # Alphanumeric value that identifies who created the API key, can also reference environment variable such as $APP_STORE_CONNECT_ISSUER_ID
