// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:fiver/core/extensions/ext_enum.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'core/enum.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions currentPlatform(Environment environment) {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android(environment);
      case TargetPlatform.iOS:
        return ios(environment);
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android(Environment environment) {
    return FirebaseOptions(
      apiKey: 'AIzaSyALdlmwlUGtDVYnhQdpGVF2H8Mf9tGlr58',
      appId: environment.getAndroidAppId(),
      messagingSenderId: '458951462646',
      projectId: 'fiver-d3dbc',
      storageBucket: 'fiver-d3dbc.appspot.com',
    );
  }

  static FirebaseOptions ios(Environment environment) {
    return FirebaseOptions(
      apiKey: 'AIzaSyDfy0VdwiXAXrTnyI9PypZNv2FBVKwTjyE',
      appId: environment.getIOSAppId(),
      messagingSenderId: '458951462646',
      projectId: 'fiver-d3dbc',
      storageBucket: 'fiver-d3dbc.appspot.com',
      iosBundleId: 'com.example.fiver',
    );
  }
}
